{% set name = "webdavclient3" %}
{% set version = "3.14.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6c04252b579bc015cec78081480c63eadf1030f382768248777c6203f059b3f5

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python  >={{ python_min }}
    - requests
    - lxml
    - python-dateutil

test:
  imports:
    - webdav3.client
  requires:
    - python {{ python_min }}  

about:
  home: https://github.com/ezhov-evgeny/webdav-client-python-3
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: 'Easy way to work with WebDAV-servers'

  description: |
    WebDAV client, based on original package https://github.com/designerror/webdav-client-python but
    uses requests instead of PyCURL
  doc_url: https://github.com/ezhov-evgeny/webdav-client-python-3
  dev_url: https://github.com/ezhov-evgeny/webdav-client-python-3

extra:
  recipe-maintainers:
    - ReimarBauer
