{% set name = "webdavclient3" %}
{% set version = "3.14.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bcd22586bb0d58abc26ca56054fd04228e704bd36073c3080f4597c1556c880d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python  >=3.5
    - pip
  run:
    - python  >=3.5
    - requests
    - lxml
    - python-dateutil

test:
  imports:
    - webdav3.client

about:
  home: https://github.com/ezhov-evgeny/webdav-client-python-3
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Easy way to work with WebDAV-servers

  description: |
    WebDAV client, based on original package https://github.com/designerror/webdav-client-python but
    uses requests instead of PyCURL
  doc_url: https://github.com/ezhov-evgeny/webdav-client-python-3
  dev_url: https://github.com/ezhov-evgeny/webdav-client-python-3

extra:
  recipe-maintainers:
    - ReimarBauer
